try {
    console.log('start of try runs here');
    unicycle;
    console.log('End of try runs here');
} catch(err){
    console.log('Error has occured:' + err + );
   
}


console.log('...then the excution continues');